# Generated by Django 4.2.1 on 2023-06-12 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_alter_profile_contract_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_start_date', models.DateField(blank=True, default=None, null=True)),
                ('contract_end_date', models.DateField(blank=True, default=None, null=True)),
                ('hours_per_week', models.FloatField(default=0)),
                ('carry_over_hours_from_last_semester', models.FloatField(default=0)),
                ('carry_over_holiday_hours_from_last_semester', models.FloatField(default=0)),
                ('supervisor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
