# Generated by Django 4.2 on 2023-05-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='carry_over_holiday_hours_from_last_semester',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='carry_over_hours_from_last_semester',
            field=models.FloatField(default=0),
        ),
    ]
