# Generated by Django 4.2.1 on 2023-06-19 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_contract_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractChange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, default=None, null=True)),
                ('hours_per_week', models.FloatField(default=0)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.contract')),
            ],
        ),
    ]
