# Generated by Django 4.2.1 on 2023-06-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contractchange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractchange',
            options={'ordering': ['id'], 'verbose_name': 'Contract Change', 'verbose_name_plural': 'Contract Changes'},
        ),
    ]
