# Generated by Django 4.2.1 on 2023-06-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_contractchange_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractchange',
            name='to_date',
            field=models.DateField(blank=True, default=None, help_text="Leave blank if you don't know when the contract change ends. Calculation will assume in this case that the contract change is till the end of the contract. If you add a second contract change, the end date of the first contract change will be set to the day before the start date of the second contract change.", null=True),
        ),
    ]
